run:
  data: "/hpf/largeprojects/davidm/data"
  project: "te_test"
  samples: samples.tsv
  MELT: "/hpf/largeprojects/davidm/vsubasri/transposable_elements/Transposable-Elements/TE_discovery/MELT/MELTv2.2.2/MELT.jar"
  genome_ref: "/hpf/largeprojects/davidm/resources/Homo_sapiens.GRCh37.75.dna_rm.primary_assembly.fa"
  element_ref: "/hpf/largeprojects/davidm/vsubasri/transposable_elements/Transposable-Elements/TE_discovery/MELT/transposon_file_list.txt"
  snpeff: "/hpf/largeprojects/davidm/resources/snpEff"
  snpeff_data: "/hpf/largeprojects/davidm/resources/snpEff/data"
  
  protein_coding_genes: "/hpf/largeprojects/davidm/resources/MELT_anno/grch37.p13.ensembl.sorted.protein.coding.genes.bed"
  exon_bed: "/hpf/largeprojects/davidm/resources/MELT_anno/hg19_UCSC_exons_canonical.bed"
  omim: "/hpf/largeprojects/davidm/resources/MELT_anno/genemap2.txt" #2020-04-09 
  gnomad: "/hpf/largeprojects/davidm/resources/MELT_anno/gnomad_v2_sv.sites.bed"
  biomart: "/hpf/largeprojects/davidm/resources/MELT_anno/BioMaRt.GrCh37.75.ensembl.mim.hgnc.entrez.txt"
  mssng_manta_counts: "/hpf/largeprojects/davidm/resources/MELT_anno/Canadian_MSSNG_parent_SVs.Manta.counts.txt"
  hpo_dir: "/hpf/largeprojects/davidm/resources/MELT_anno/phenotype.hpoa"
  sv_counts: [mssng_manta_counts]





