#!/bin/bash

#SBATCH -c 8
#SBATCH -t 0-12:00
#SBATCH --mem=25G
#SBATCH -o 271116_%j.out

module load samtools/1.9 bwa/0.7.17 anaconda/4.6.14

source /hpf/tools/centos6/anaconda/4.6.14/bin/activate

conda activate TransposableElements

