#!/usr/bin/env Rscript

# Germline TE Visualization - Clinical Associations
# TE counts by clinical variables, cancer status, ancestry comparisons

# Source common setup and load data
source("/Users/briannelaverty/Documents/R_Malkin/te/scripts/viz/00_viz_common_setup.R")
source("/Users/briannelaverty/Documents/R_Malkin/te/scripts/viz/00_viz_load_data_germline.R")

cat("Running 02_te_viz_germline_02_clinical.R...\n")

#### TE COUNT ####
types <- c(NA, "LINE1", "ALU", "SVA")
x_cancer_tp53 <- expression("Cancer and germline " * italic("TP53") * " status")
x_tp53 <- expression("Germline " * italic("TP53") * " status")
covar_med <- c("med_cov", "total_reads", "med_read_len", "pct_chimeras", "avg_quality", "tumor_type", "predicted_ancestry_thres")

# all
# df with kics, lfs with cancer, and hostseq
te_cancer_hostseq <- te_all %>%
  filter(cohort == "HostSeq") %>%  # Filter rows where cohort is HostSeq
  bind_rows(te_aff)  # Combine with te_aff dataframe

# Save the 4 plots generated by generate_plots
cat("Plotting te_all with hostseq with kruskal\n")
plots_kruskal_cancer <- vector("list", length(types))
for (i in seq_along(types)) {
  plots_kruskal_cancer[[i]] <- write_output(
    quote(plot_count_kruskal(te_cancer_hostseq, type=types[i], log_scale=TRUE, group="cancer_cohort", x_lab=x_cancer_tp53, y_lab="Repeat frequency", chr=NA)),
    paste0("Kruskal plot output (cancer cohort, type=", ifelse(is.na(types[i]), "all", types[i]), ")")
  )
  cat(paste0("Plotting: te_count_cancer_cluster_all_", ifelse(is.na(types[i]), "all", types[i]), ".pdf\n"))
  titled_print(plots_kruskal_cancer[[i]], paste0("Kruskal plot (cancer cohort, type=", ifelse(is.na(types[i]), "all", types[i]), ")"))
  ggsave(paste0(plot_dir, "counts_cohort/te_count_cancer_cluster_all_", ifelse(is.na(types[i]), "all", types[i]), ".pdf"), plot=plots_kruskal_cancer[[i]], width = 3, height = 5)
}

# Generate faceted plots by ancestry
cat("Plotting te_all with hostseq with kruskal faceted by ancestry\n")
plots_kruskal_cancer_ancestry <- vector("list", length(types))
for (i in seq_along(types)) {
  plots_kruskal_cancer_ancestry[[i]] <- write_output(
    quote(plot_count_kruskal_facet_ancestry(te_cancer_hostseq, type=types[i], log_scale=FALSE, group="cancer_cohort", x_lab=x_cancer_tp53, y_lab="Repeat frequency", chr=NA)),
    paste0("Kruskal plot output faceted by ancestry (cancer cohort, type=", ifelse(is.na(types[i]), "all", types[i]), ")")
  )
  cat(paste0("Plotting: te_count_cancer_cluster_all_", ifelse(is.na(types[i]), "all", types[i]), "_ancestry.pdf\n"))
  titled_print(plots_kruskal_cancer_ancestry[[i]], paste0("Kruskal plot faceted by ancestry (cancer cohort, type=", ifelse(is.na(types[i]), "all", types[i]), ")"))
  ggsave(paste0(plot_dir, "counts_cohort/te_count_cancer_cluster_all_", ifelse(is.na(types[i]), "all", types[i]), "_ancestry.pdf"), plot=plots_kruskal_cancer_ancestry[[i]], width = 32, height = 24)
}

# Linear model for all types in te_cancer_hostseq
cat("Plotting linear model for te_cancer_hostseq\n")
plots_lm_cancer <- vector("list", length(types))
for (i in seq_along(types)) {
  y_label <- ifelse(is.na(types[i]), "Total TE count", paste0(types[i], " count"))
  cat(paste0("\n========================================\n"))
  cat(paste0("  Linear model output (cancer cohort, type=", ifelse(is.na(types[i]), "all", types[i]), ")\n"))
  cat(paste0("========================================\n"))
  plots_lm_cancer[[i]] <- plot_count_lm(te_cancer_hostseq, type=types[i], group="cancer_cohort", y_lab=y_label, covariates = covar_med, residuals=FALSE, log_scale=FALSE, x_lab=x_cancer_tp53, min_samples=5, chr=NA)
  cat("\n")
  cat(paste0("Plotting: te_count_lm_cancer_hostseq_", ifelse(is.na(types[i]), "all", types[i]), ".pdf\n"))
  titled_print(plots_lm_cancer[[i]], paste0("Linear model (cancer cohort, type=", ifelse(is.na(types[i]), "all", types[i]), ")"))
  ggsave(paste0(plot_dir, "counts_cohort/te_count_lm_cancer_hostseq_", ifelse(is.na(types[i]), "all", types[i]), ".pdf"), plot=plots_lm_cancer[[i]], width=5, height=5)
}

# Linear model faceted by ancestry
cat("Plotting linear model for te_cancer_hostseq faceted by ancestry\n")
plots_lm_cancer_ancestry <- vector("list", length(types))
for (i in seq_along(types)) {
  y_label <- ifelse(is.na(types[i]), "Total TE count", paste0(types[i], " count"))
  cat(paste0("\n========================================\n"))
  cat(paste0("  Linear model output faceted by ancestry (cancer cohort, type=", ifelse(is.na(types[i]), "all", types[i]), ")\n"))
  cat(paste0("========================================\n"))
  plots_lm_cancer_ancestry[[i]] <- plot_count_lm_facet_ancestry(te_cancer_hostseq, type=types[i], group="cancer_cohort", y_lab=y_label, covariates = covar_med, residuals=FALSE, log_scale=FALSE, x_lab=x_cancer_tp53, min_samples=5, chr=NA)
  cat("\n")
  cat(paste0("Plotting: te_count_lm_cancer_hostseq_", ifelse(is.na(types[i]), "all", types[i]), "_ancestry.pdf\n"))
  titled_print(plots_lm_cancer_ancestry[[i]], paste0("Linear model faceted by ancestry (cancer cohort, type=", ifelse(is.na(types[i]), "all", types[i]), ")"))
  ggsave(paste0(plot_dir, "counts_cohort/te_count_lm_cancer_hostseq_", ifelse(is.na(types[i]), "all", types[i]), "_ancestry.pdf"), plot=plots_lm_cancer_ancestry[[i]], width=32, height=24)
}

# affected
cat("Plotting te_aff with kruskal\n")
plots_wilcox_aff <- vector("list", length(types))
for (i in seq_along(types)) {
  plots_wilcox_aff[[i]] <- write_output(
    quote(plot_count_wilcox(te_aff, chr=NA, type=types[i], group="TP53_status", x_lab=x_tp53, y_lab="Repeat frequency")),
    paste0("Wilcoxon plot output (affected, type=", ifelse(is.na(types[i]), "all", types[i]), ")")
  )
  cat(paste0("Plotting: te_count_wilcox_aff_", ifelse(is.na(types[i]), "all", types[i]), ".pdf\n"))
  titled_print(plots_wilcox_aff[[i]], paste0("Wilcoxon plot (affected, type=", ifelse(is.na(types[i]), "all", types[i]), ")"))
  ggsave(paste0(plot_dir, "counts_cohort/te_count_wilcox_aff_", ifelse(is.na(types[i]), "all", types[i]), ".pdf"), plot=plots_wilcox_aff[[i]], width = 3, height = 5)
}

# Linear model for all types in te_aff
cat("Plotting linear model for te_aff\n")
plots_lm_aff <- vector("list", length(types))
for (i in seq_along(types)) {
  y_label <- ifelse(is.na(types[i]), "Total TE count", paste0(types[i], " count"))
  plots_lm_aff[[i]] <- write_output(
    quote(plot_count_lm(te_aff, type=types[i], group="TP53_status", y_lab=y_label, covariates = covar_med, residuals=FALSE, log_scale=FALSE, x_lab=x_tp53, min_samples=5, chr=NA)),
    paste0("Linear model output (affected, type=", ifelse(is.na(types[i]), "all", types[i]), ")")
  )
  cat(paste0("Plotting: te_count_lm_aff_", ifelse(is.na(types[i]), "all", types[i]), ".pdf\n"))
  titled_print(plots_lm_aff[[i]], paste0("Linear model (affected, type=", ifelse(is.na(types[i]), "all", types[i]), ")"))
  ggsave(paste0(plot_dir, "counts_cohort/te_count_lm_aff_", ifelse(is.na(types[i]), "all", types[i]), ".pdf"), plot=plots_lm_aff[[i]], width=5, height=5)
}

# Bootstrap for all types in te_aff (returns two plots)
cat("Running bootstrap test for te_aff\n")
for (t in types) {
  boot_res <- bootstrap_test(te_aff, "TP53_status", ifelse(is.na(t), "total", t), mean, n_bootstraps = 10000, step_size=100)
  cat(paste0("\n===== Plotting: te_count_bootstrap_aff_dist_", ifelse(is.na(t), "all", t), ".pdf =====\n"))
  titled_print(boot_res$dist_plot, paste0("Bootstrap test (affected, type=", ifelse(is.na(t), "all", t), ") - Distribution Plot"))
  ggsave(paste0(plot_dir, "counts_cohort/te_count_bootstrap_aff_dist_", ifelse(is.na(t), "all", t), ".pdf"), plot=boot_res$dist_plot, width=3, height=5)
  cat(paste0("\n===== Plotting: te_count_bootstrap_aff_pval_", ifelse(is.na(t), "all", t), ".pdf =====\n"))
  titled_print(boot_res$pval_plot, paste0("Bootstrap test (affected, type=", ifelse(is.na(t), "all", t), ") - P-value Convergence Plot"))
  ggsave(paste0(plot_dir, "counts_cohort/te_count_bootstrap_aff_pval_", ifelse(is.na(t), "all", t), ".pdf"), plot=boot_res$pval_plot, width=3, height=5)
}

#### CANCER STATUS COMPARISON (Affected vs Unaffected) ####
cat("\n===== CANCER STATUS COMPARISON (AFFECTED vs UNAFFECTED) =====\n")
tryCatch({
  # Compare TE burden between affected and unaffected samples in te_aff_unaff
  # This analysis is only meaningful for samples where we have both affected and unaffected

  cat("\nComparing TE burden: Affected vs Unaffected\n")
  cat("Dataset: te_aff_unaff (LFS + KICS, excluding Taylor and HostSeq)\n\n")

  # Create count matrix for te_aff_unaff if not already created
  if (!exists("te_aff_unaff")) {
    te_aff_unaff <- te_all %>% filter(cohort != "Taylor" & cohort != "HostSeq")
  }

  # Add Cancer status indicator for all samples
  te_aff_unaff <- te_aff_unaff %>%
    mutate(Cancer_status = ifelse(tumor_type != "U", "Affected", "Unaffected"))

  # Summary statistics
  cancer_summary <- te_aff_unaff %>%
    group_by(Cancer_status) %>%
    summarise(
      n_samples = n(),
      mean_total = mean(total, na.rm = TRUE),
      median_total = median(total, na.rm = TRUE),
      sd_total = sd(total, na.rm = TRUE)
    )

  write_output(quote(cancer_summary), "Summary: TE burden by Cancer status (Affected vs Unaffected)")

  # Wilcoxon test for total TE count
  if (sum(te_aff_unaff$Cancer_status == "Affected") > 0 &&
      sum(te_aff_unaff$Cancer_status == "Unaffected") > 0) {

    wilcox_cancer <- wilcox.test(
      total ~ Cancer_status,
      data = te_aff_unaff,
      alternative = "two.sided"
    )

    cat("\nWilcoxon test: Total TE count ~ Cancer status\n")
    cat("  p-value:", wilcox_cancer$p.value, "\n")
    write_output(quote(wilcox_cancer), "Wilcoxon test: Total TE count by Cancer status")

    # Boxplot
    p_cancer <- ggplot(te_aff_unaff, aes(x = Cancer_status, y = total, fill = Cancer_status)) +
      geom_boxplot(outlier.shape = NA) +
      geom_jitter(width = 0.2, alpha = 0.3) +
      labs(
        title = "TE Burden: Affected vs Unaffected",
        subtitle = paste0("p = ", format(wilcox_cancer$p.value, digits = 3)),
        x = "Cancer Status",
        y = "Total TE Count"
      ) +
      theme_minimal() +
      theme(legend.position = "none")

    print(p_cancer)
    ggsave(paste0(plot_dir, "counts_cohort/te_count_cancer_status_comparison.pdf"),
           plot = p_cancer, width = 6, height = 5)

    # Test by TE type
    cat("\nTesting individual TE types:\n")
    te_types <- c("LINE1", "ALU", "SVA", "HERVK")
    cancer_type_results <- data.frame()

    for (te_type in te_types) {
      if (te_type %in% colnames(te_aff_unaff)) {
        test <- wilcox.test(
          te_aff_unaff[[te_type]] ~ te_aff_unaff$Cancer_status,
          alternative = "two.sided"
        )
        cancer_type_results <- rbind(cancer_type_results, data.frame(
          TE_type = te_type,
          p_value = test$p.value,
          median_affected = median(te_aff_unaff[[te_type]][te_aff_unaff$Cancer_status == "Affected"], na.rm = TRUE),
          median_unaffected = median(te_aff_unaff[[te_type]][te_aff_unaff$Cancer_status == "Unaffected"], na.rm = TRUE)
        ))
      }
    }

    # Adjust p-values
    cancer_type_results$p_adj <- p.adjust(cancer_type_results$p_value, method = "BH")
    write_output(quote(cancer_type_results), "TE type comparison: Affected vs Unaffected")
    write.csv(cancer_type_results, paste0(r_dir_files, "cancer_status_te_type_comparison.csv"), row.names = FALSE)
  }

  # Test specific TEs for cancer status (within LFS samples with both affected and unaffected)
  cat("\nTesting for specific TEs associated with cancer status...\n")
  te_lfs_cancer <- te_lfs_expand %>%
    filter(!is.na(Cancer))  # Make sure Cancer status is defined

  if (nrow(te_lfs_cancer) > 0) {
    te_lfs_count <- te_lfs %>% filter(!is.na(tumor_type))

    te_cancer_specific <- test_specific_tes_by_group(
      te_expand = te_lfs_cancer,
      te_count = te_lfs_count,
      group_column = "Cancer",
      min_samples_with = 3,
      min_samples_without = 3,
      output_dir = r_dir_files,
      output_prefix = "specific_tes_cancer_status"
    )

    if (!is.null(te_cancer_specific)) {
      write_output(quote(head(te_cancer_specific$full_results, 20)),
                   "Top 20 TEs by cancer status (Affected vs Unaffected in LFS)")
    }
  }

}, error = function(e) {
  cat("Warning: Could not perform cancer status comparison:", e$message, "\n")
})

#### BY TT ####
# count by tumour type
cat("\n===== Plotting: Kruskal by tumour type (te_aff) =====\n")
plots_kruskal_nogroup <- vector("list", length(types))
for (i in seq_along(types)) {
  plots_kruskal_nogroup[[i]] <- write_output(
    quote(plot_count_kruskal_nogroup(te_aff, type=types[i], chr=NA, min=5, column="tumor_type", y_lab="Rare repeat count", x_lab="Tumour type", log_scale = TRUE)),
    paste0("Kruskal by tumour type (te_aff, type=", ifelse(is.na(types[i]), "all", types[i]), ")")
  )
  titled_print(plots_kruskal_nogroup[[i]], paste0("Kruskal by tumour type (te_aff, type=", ifelse(is.na(types[i]), "all", types[i]), ")"))
  ggsave(paste0(plot_dir, "counts_tumour_type/te_count_tt_aff_", ifelse(is.na(types[i]), "all", types[i]), ".pdf"), plot=plots_kruskal_nogroup[[i]], width = 9, height = 5)
}

cat(" Plotting: Kruskal by tumour type (te_kics) \n")
# Define p_tt_kics for plotting for all types
plots_kruskal_nogroup_kics <- vector("list", length(types))
for (i in seq_along(types)) {
  plots_kruskal_nogroup_kics[[i]] <- write_output(
    quote(plot_count_kruskal_nogroup(te_kics, type=types[i], chr=NA, min=5, column="tumor_type", y_lab="Rare repeat count", x_lab="Tumour type", log_scale = TRUE)),
    paste0("Kruskal by tumour type (te_kics, type=", ifelse(is.na(types[i]), "all", types[i]), ")")
  )
  cat(paste0("Plotting: te_count_tt_kics_", ifelse(is.na(types[i]), "all", types[i]), ".pdf =====\n"))
  titled_print(plots_kruskal_nogroup_kics[[i]], paste0("Kruskal by tumour type (te_kics, type=", ifelse(is.na(types[i]), "all", types[i]), ")"))
  ggsave(paste0(plot_dir, "counts_tumour_type/te_count_tt_kics_", ifelse(is.na(types[i]), "all", types[i]), ".pdf"), plot=plots_kruskal_nogroup_kics[[i]], width = 9, height = 5)
}

cat(" Plotting: Kruskal by tumour type (te_lfs) \n")
# Define plots for LFS cohort
plots_kruskal_nogroup_lfs <- vector("list", length(types))
for (i in seq_along(types)) {
  plots_kruskal_nogroup_lfs[[i]] <- write_output(
    quote(plot_count_kruskal_nogroup(te_lfs, type=types[i], chr=NA, min=5, column="tumor_type", y_lab="Rare repeat count", x_lab="Tumour type", log_scale = TRUE)),
    paste0("Kruskal by tumour type (te_lfs, type=", ifelse(is.na(types[i]), "all", types[i]), ")")
  )
  cat(paste0("Plotting: te_count_tt_lfs_", ifelse(is.na(types[i]), "all", types[i]), ".pdf =====\n"))
  titled_print(plots_kruskal_nogroup_lfs[[i]], paste0("Kruskal by tumour type (te_lfs, type=", ifelse(is.na(types[i]), "all", types[i]), ")"))
  ggsave(paste0(plot_dir, "counts_tumour_type/te_count_tt_lfs_", ifelse(is.na(types[i]), "all", types[i]), ".pdf"), plot=plots_kruskal_nogroup_lfs[[i]], width = 9, height = 5)
}

# Export top 10% samples by total insertions
cat("\n===== EXPORTING TOP 10% SAMPLES BY TOTAL INSERTIONS =====\n")
top10_threshold <- quantile(te_aff$total, 0.90, na.rm = TRUE)
te_aff_top10 <- te_aff %>% filter(total >= top10_threshold)
cat("Top 10% threshold:", top10_threshold, "\n")
cat("Number of samples in top 10%:", nrow(te_aff_top10), "\n")
write.csv(te_aff_top10, paste0(r_dir_files, "te_aff_top10_samples.csv"), row.names = FALSE, quote = FALSE)
cat("Exported te_aff_top10_samples.csv\n")

# Export outlier samples by tumor type (types with >=3 samples)
cat("\n===== EXPORTING OUTLIER SAMPLES BY TUMOR TYPE =====\n")
outlier_samples <- te_aff %>%
  group_by(tumor_type) %>%
  filter(n() >= 3) %>%
  mutate(
    Q1 = quantile(total, 0.25, na.rm = TRUE),
    Q3 = quantile(total, 0.75, na.rm = TRUE),
    IQR = Q3 - Q1,
    lower_bound = Q1 - 1.5 * IQR,
    upper_bound = Q3 + 1.5 * IQR,
    is_outlier = total < lower_bound | total > upper_bound
  ) %>%
  filter(is_outlier) %>%
  ungroup() %>%
  select(-Q1, -Q3, -IQR, -lower_bound, -upper_bound, -is_outlier)

cat("Number of outlier samples:", nrow(outlier_samples), "\n")
if (nrow(outlier_samples) > 0) {
  cat("Outliers by tumor type:\n")
  print(table(outlier_samples$tumor_type))
  write.csv(outlier_samples, paste0(r_dir_files, "te_aff_outliers_by_tumor_type.csv"), row.names = FALSE, quote = FALSE)
  cat("Exported te_aff_outliers_by_tumor_type.csv\n")
} else {
  cat("No outliers detected\n")
}

cat("Plotting: TE count by tumour type and TP53 group (te_aff) \n")
# count by tumour type and grouped by group
plots_tt_group <- vector("list", length(types))
for (i in seq_along(types)) {
  plots_tt_group[[i]] <- write_output(
    quote(plot_count_tt(te_aff, chr=NA, type=types[i], group="TP53_status", min=2, y_lab="Repeat count", legend_title=x_tp53, log_scale = TRUE)),
    paste0("TE count by tumour type and TP53 group (te_aff, type=", ifelse(is.na(types[i]), "all", types[i]), ")")
  )
  cat(paste0("Plotting: te_count_tt_aff_tp53_", ifelse(is.na(types[i]), "all", types[i]), ".pdf =====\n"))
  titled_print(plots_tt_group[[i]], paste0("TE count by tumour type and TP53 group (te_aff, type=", ifelse(is.na(types[i]), "all", types[i]), ")"))
  ggsave(paste0(plot_dir, "counts_tumour_type/te_count_tt_aff_tp53_", ifelse(is.na(types[i]), "all", types[i]), ".pdf"), plot=plots_tt_group[[i]], width = 9, height = 5)
}

# specific te by tumour type
cat("Performing Fisher's test by tumour type \n")
specific_te_tt <- write_output(
  quote(as.data.frame(fisher_test_by_tumor_type(te_aff_expand, min_samples_tt=10, min_samples_te=5))),
  "Fisher test by tumour type (te_aff_expand)"
)
write_output(quote(print(head(specific_te_tt))), "Head of specific_te_tt")

# samples with significant TE
cat("Filtering significant TEs by tumour type\n")
specific_te_tt_sig <- specific_te_tt %>% filter(fisher_p_value_BH < 0.05)

# Get contingency tables in long format for CSV export
sig_te_tt_tables_long <- write_output(
  quote(get_sig_te_contingency_tables_long(te_aff_expand, specific_te_tt_sig, min_samples_tt=10)),
  "Contingency tables for significant TE by tumour type (te_aff_expand)"
)

# Save results to files directory
write.csv(specific_te_tt_sig, paste0(r_dir_files, "specific_te_tt_sig.csv"), row.names=FALSE)
write.csv(sig_te_tt_tables_long, paste0(r_dir_files, "specific_te_tt_table.csv"), row.names=FALSE)
cat("Saved specific_te_tt_sig.csv and specific_te_tt_table.csv\n")


#### COUNT BY CLINICAL VARIABLES ####
# by cluster
cat("Plotting: te_count_lfs_cluster.pdf \n")
plots_kruskal_cluster <- vector("list", length(types))
for (i in seq_along(types)) {
  plots_kruskal_cluster[[i]] <- write_output(
    quote(plot_count_kruskal(te_lfs, chr=NA, type=types[i], group="cluster", x_lab="Cluster", y_lab="Repeat count", log_scale=TRUE)),
    paste0("Kruskal by cluster (te_lfs, type=", ifelse(is.na(types[i]), "all", types[i]), ")")
  )
  titled_print(plots_kruskal_cluster[[i]], paste0("Kruskal by cluster (te_lfs, type=", ifelse(is.na(types[i]), "all", types[i]), ")"))
  ggsave(paste0(plot_dir, "counts_clinical_lfs/te_count_lfs_cluster_", ifelse(is.na(types[i]), "all", types[i]), ".pdf"), plot=plots_kruskal_cluster[[i]], width = 9, height = 5)
}

# by inheritance
cat("Plotting: te_count_lfs_inheritance \n")
te_lfs <- te_lfs[!grepl("DELETE", te_lfs$inheritance), ]
plots_kruskal_inheritance <- vector("list", length(types))
for (i in seq_along(types)) {
  plots_kruskal_inheritance[[i]] <- write_output(
    quote(plot_count_kruskal(te_lfs, chr=NA, type=types[i], group="inheritance", x_lab="Inheritance", y_lab="Repeat count", log_scale = TRUE)),
    paste0("Kruskal by inheritance (te_lfs, type=", ifelse(is.na(types[i]), "all", types[i]), ")")
  )
  titled_print(plots_kruskal_inheritance[[i]], paste0("Kruskal by inheritance (te_lfs, type=", ifelse(is.na(types[i]), "all", types[i]), ")"))
  ggsave(paste0(plot_dir, "counts_clinical_lfs/te_count_lfs_inheritance_", ifelse(is.na(types[i]), "all", types[i]), ".pdf"), plot=plots_kruskal_inheritance[[i]], width = 9, height = 5)
}

# by variant location
cat("Plotting: te_count_lfs_varloc.pdf\n")
plots_kruskal_varloc <- vector("list", length(types))
for (i in seq_along(types)) {
  plots_kruskal_varloc[[i]] <- write_output(
    quote(plot_count_kruskal(te_lfs, chr=NA, type=types[i], group="Variant_location", x_lab="TP53 variant location", y_lab="Repeat count", log_scale = TRUE)),
    paste0("Kruskal by variant location (te_lfs, type=", ifelse(is.na(types[i]), "all", types[i]), ")")
  )
  titled_print(plots_kruskal_varloc[[i]], paste0("Kruskal by variant location (te_lfs, type=", ifelse(is.na(types[i]), "all", types[i]), ")"))
  ggsave(paste0(plot_dir, "counts_clinical_lfs/te_count_lfs_varloc_", ifelse(is.na(types[i]), "all", types[i]), ".pdf"), plot=plots_kruskal_varloc[[i]], width = 9, height = 5)
}

# by variant classification
cat("Plotting: te_count_lfs_varclass.pdf \n")
plots_kruskal_varclass <- vector("list", length(types))
for (i in seq_along(types)) {
  plots_kruskal_varclass[[i]] <- write_output(
    quote(plot_count_kruskal(te_lfs, chr=NA, type=types[i], group="Variant_Classification", x_lab="TP53 variant classification", y_lab="Repeat count", log_scale = TRUE)),
    paste0("Kruskal by variant classification (te_lfs, type=", ifelse(is.na(types[i]), "all", types[i]), ")")
  )
  titled_print(plots_kruskal_varclass[[i]], paste0("Kruskal by variant classification (te_lfs, type=", ifelse(is.na(types[i]), "all", types[i]), ")"))
  ggsave(paste0(plot_dir, "counts_clinical_lfs/te_count_lfs_varclass_", ifelse(is.na(types[i]), "all", types[i]), ".pdf"), plot=plots_kruskal_varclass[[i]], width = 9, height = 5)
}

# count by age
cat("Plotting: te_count_age_kics_all \n")
plots_age <- vector("list", length(types))
for (i in seq_along(types)) {
  plots_age[[i]] <- write_output(
    quote(plot_count_age(te_kics, chr=NA, type=types[i], y_lab="Repeat count")),
    paste0("TE count by age (te_kics, type=", ifelse(is.na(types[i]), "all", types[i]), ")")
  )
  titled_print(plots_age[[i]], paste0("TE count by age (te_kics, type=", ifelse(is.na(types[i]), "all", types[i]), ")"))
  ggsave(paste0(plot_dir, "counts_clinical_kics/te_count_age_kics_", ifelse(is.na(types[i]), "all", types[i]), ".pdf"), plot=plots_age[[i]], width = 9, height = 5)
}

# lesion type
cat("Plotting: te_count_lesion_type_aff_all\n")
plots_lesion_type <- vector("list", length(types))
for (i in seq_along(types)) {
  plots_lesion_type[[i]] <- write_output(
    quote(plot_count_kruskal(te_aff, chr=NA, type=types[i], group="lesion_type", x_lab="Lesion type", y_lab="Repeat count", log_scale=TRUE)),
    paste0("Kruskal by lesion type (te_aff, type=", ifelse(is.na(types[i]), "all", types[i]), ")")
  )
  titled_print(plots_lesion_type[[i]], paste0("Kruskal by lesion type (te_aff, type=", ifelse(is.na(types[i]), "all", types[i]), ")"))
  ggsave(paste0(plot_dir, "counts_clinical_kics/te_count_lesion_type_aff_", ifelse(is.na(types[i]), "all", types[i]), ".pdf"), plot=plots_lesion_type[[i]], width = 9, height = 5)
}

cat("Plotting: te_count_lm_lesion_type_aff_all.pdf\n")
# Define p_lm_lesion_type and boot_lesion_type before plotting
p_lm_lesion_type <- write_output(
  quote(plot_count_lm(te_aff, min_samples=5, residuals=FALSE, group="lesion_type", log_scale=TRUE, covariates = covar_med, x_lab="Lesion type", y_lab="Repeat count", type=NA, chr=NA)),
  "Linear model by lesion type (te_aff, all types, log scale)"
)
titled_print(p_lm_lesion_type, "Linear model by lesion type (te_aff, all types, log scale)")
ggsave(paste0(plot_dir, "counts_clinical_kics/te_count_lm_lesion_type_aff_all.pdf"), plot=p_lm_lesion_type, width = 9, height = 5)

# disease state
plots_disease_state <- vector("list", length(types))
for (i in seq_along(types)) {
  plots_disease_state[[i]] <- write_output(
    quote(plot_count_kruskal(te_aff, chr=NA, type=types[i], group="disease_state", x_lab="Disease state", y_lab="Repeat count", log_scale=TRUE)),
    paste0("Kruskal by disease state (te_aff, type=", ifelse(is.na(types[i]), "all", types[i]), ")")
  )
  titled_print(plots_disease_state[[i]], paste0("Kruskal by disease state (te_aff, type=", ifelse(is.na(types[i]), "all", types[i]), ")"))
  ggsave(paste0(plot_dir, "counts_clinical_kics/te_count_disease_state_aff_", ifelse(is.na(types[i]), "all", types[i]), ".png"), plot=plots_disease_state[[i]], width = 9, height = 5)
}
p_kruskal_disease_state_all <- write_output(
  quote(plot_count_kruskal(te_aff, type=NA, chr=NA, group="disease_state", x_lab="Disease state", y_lab="TE count", log_scale=TRUE)),
  "Kruskal by disease state (te_aff, all types, log_scale)"
)

# sex
p_lm_sex <- write_output(
  quote(plot_count_lm(te_aff, min_samples=5, residuals=FALSE, group="sex", log_scale=TRUE, covariates = covar_med, x_lab="Sex", y_lab="Total TE count", type=NA, chr=NA)),
  "Linear model by sex (te_aff, all types, log scale)"
)
titled_print(p_lm_sex, "Linear model by sex (te_aff, all types, log scale)")
ggsave(paste0(plot_dir, "counts_clinical_kics/te_count_lm_sex_aff_all.png"), plot=p_lm_sex, width = 9, height = 5)

#### SAMPLE TYPE ANALYSIS (KICS) ####
cat("\n===== SAMPLE TYPE ANALYSIS (KICS) =====\n")

# Load and prepare KICS sample type data
kics_sample_type <- prep_kics_sample_type(
  "/Users/briannelaverty/Documents/R_Malkin/clinical/kics_germline_sample_type.csv"
)

# Analyze TE burden by sample type
sample_type_results <- analyze_sample_type(
  te_data = te_aff,
  sample_type_data = kics_sample_type,
  types = types,
  plot_dir = plot_dir,
  filter_types = c("Blood", "Fibroblasts", "Tissue (fresh)"),
  min_samples = 3
)

# Print plots with titles
for (i in seq_along(types)) {
  type_label <- ifelse(is.na(types[i]), "all", types[i])
  titled_print(sample_type_results$plots[[i]],
               paste0("Kruskal by sample type (KICS, type=", type_label, ")"))
}

#### ANCESTRY ANALYSIS ####
cat("\n========================================\n")
cat("ANCESTRY ANALYSIS\n")
cat("========================================\n\n")

# Merge location windows with ancestry using same approach as processing script
location_ancestry <- write_output(
  quote(merge_location_ancestry(location_100kb_g, ancestry)),
  "Merging location windows with ancestry"
)

# Identify clinical columns to exclude from PCA/UMAP
clinical_cols <- c("sample", "predicted_ancestry_thres", "mapped_label", "age", "sex", "cohort", "tumor_type",
                   "TP53_germline", "affected", "cancer", "age_diagnosis", "TP53_status")
exclude_cols <- intersect(clinical_cols, colnames(location_ancestry))

# Perform PCA on location windows
pca_results <- write_output(
  quote(perform_location_pca(location_ancestry, exclude_cols = exclude_cols)),
  "Performing PCA on location windows"
)

# Perform UMAP on location windows
umap_results <- write_output(
  quote(perform_location_umap(location_ancestry, exclude_cols = exclude_cols)),
  "Performing UMAP on location windows"
)

# Plot PCA colored by predicted_ancestry_thres
p_pca_ancestry <- write_output(
  quote(plot_pca_ancestry(pca_results, color_by = "predicted_ancestry_thres",
                         output_dir = plot_dir, plot_prefix = "germline")),
  "Plotting PCA colored by predicted ancestry"
)
titled_print(p_pca_ancestry, "PCA of TE Location Windows by Predicted Ancestry")

# Plot PCA colored by mapped_label
p_pca_mapped <- write_output(
  quote(plot_pca_ancestry(pca_results, color_by = "mapped_label",
                         output_dir = plot_dir, plot_prefix = "germline")),
  "Plotting PCA colored by mapped label"
)
titled_print(p_pca_mapped, "PCA of TE Location Windows by Mapped Label")

# Plot UMAP colored by predicted_ancestry_thres
p_umap_ancestry <- write_output(
  quote(plot_umap_ancestry(umap_results, color_by = "predicted_ancestry_thres",
                          output_dir = plot_dir, plot_prefix = "germline")),
  "Plotting UMAP colored by predicted ancestry"
)
titled_print(p_umap_ancestry, "UMAP of TE Location Windows by Predicted Ancestry")

# Plot UMAP colored by mapped_label
p_umap_mapped <- write_output(
  quote(plot_umap_ancestry(umap_results, color_by = "mapped_label",
                          output_dir = plot_dir, plot_prefix = "germline")),
  "Plotting UMAP colored by mapped label"
)
titled_print(p_umap_mapped, "UMAP of TE Location Windows by Mapped Label")

# Plot count LM grouped by predicted_ancestry_thres
# Create palette for ancestry groups
ancestry_palette <- scales::hue_pal()(length(unique(te_aff$predicted_ancestry_thres[!is.na(te_aff$predicted_ancestry_thres)])))

p_lm_ancestry_pred <- write_output(
  quote(plot_count_lm(te_aff, min_samples=5, residuals=FALSE, group="predicted_ancestry_thres",
                      log_scale=TRUE, covariates = covar_med, x_lab="Predicted Ancestry",
                      y_lab="Total TE count", type=NA, chr=NA, fill_palette=ancestry_palette)),
  "Linear model by predicted ancestry thres (te_aff, all types, log scale)"
)
titled_print(p_lm_ancestry_pred, "Linear model by predicted ancestry thres (te_aff, all types, log scale)")
ggsave(paste0(plot_dir, "ancestry/te_count_lm_predicted_ancestry_thres_aff_all.png"), plot=p_lm_ancestry_pred, width = 9, height = 5)

# Plot count LM grouped by mapped_label
mapped_label_palette <- scales::hue_pal()(length(unique(te_aff$mapped_label[!is.na(te_aff$mapped_label)])))

p_lm_ancestry_mapped <- write_output(
  quote(plot_count_lm(te_aff, min_samples=5, residuals=FALSE, group="mapped_label",
                      log_scale=TRUE, covariates = covar_med, x_lab="Mapped Label",
                      y_lab="Total TE count", type=NA, chr=NA, fill_palette=mapped_label_palette)),
  "Linear model by mapped label (te_aff, all types, log scale)"
)
titled_print(p_lm_ancestry_mapped, "Linear model by mapped label (te_aff, all types, log scale)")
ggsave(paste0(plot_dir, "ancestry/te_count_lm_mapped_label_aff_all.png"), plot=p_lm_ancestry_mapped, width = 9, height = 5)

cat("✓ Clinical associations completed successfully\n")
